all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # change this to your pod CIDR
    pod_cidr: "172.42.0.0/16"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ProxyCommand="ssh cornaca@mcnode43 -W %h:%p"'
    ansible_user: ubuntu

# edit with IP of your control plane and workers
control_plane:
  hosts:
    kashef-albaraa-ctl:
      ansible_host: 10.180.100.3

workers:
  hosts:
    kashef-albaraa-w1:
      ansible_host: 10.180.100.4

others:
  hosts:
    kashef-albaraa-AI:
      ansible_host: 10.180.100.2